[workspace]
resolver = "2"

members = [
    "rustreexo",
    "server",
    "input-generator",
]

exclude = [
    "circuit/script",
    "circuit/program/utreexo",
    "circuit/script/bin",
]

[profile.release]
debug = true
