edition = "2021"
# imports
reorder_imports = true
imports_granularity = "Item"
group_imports = "StdExternalCrate"

# lines
newline_style = "Unix"

force_explicit_unsafe = true

chain_split_single_line = true
chain_width = 30

array_width = 40
attr_fn_like_width = 40

fn_call_width = 40

# comments
format_code_in_doc_comments = true

# macros
format_macro_matchers = true
