name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install sp1
      run: |
        curl -L https://sp1.succinct.xyz | bash
        ~/.sp1/bin/sp1up
        ~/.sp1/bin/cargo-prove prove --version
    - name: Build circuit
      run: |
        cd circuit/program/utreexo
        ~/.sp1/bin/cargo-prove prove build
    - name: Build
      run: cargo build --workspace --exclude btcx-program-utreexo --exclude utreexo-script
    - name: Run unit tests
      run: cargo test --workspace --exclude btcx-program-utreexo --exclude utreexo-script
    

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Clippy
      run: rustup component add clippy
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Run Clippy
      run: cargo clippy -- -D warnings

  end-to-end:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install sp1
      run: |
        curl -L https://sp1.succinct.xyz | bash
        ~/.sp1/bin/sp1up
        ~/.sp1/bin/cargo-prove prove --version
    - name: Run end to end tests
      run: python3 run-end-to-end.py --test
