name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install sp1
      run curl -L https://sp1.succinct.xyz | bash
    - run: sp1up
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Clippy
      run: rustup component add clippy
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Run Clippy
      run: cargo clippy -- -D warnings

  end-to-end:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run end to end tests
      run: python3 run-end-to-end.py --test
