name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Cache Rust dependencies and build artifacts
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # - name: Install sp1
    #   run: |
    #     curl -L https://sp1up.succinct.xyz | bash
    #     ~/.sp1/bin/sp1up
    #     ~/.sp1/bin/cargo-prove prove --version

    # - name: Install clang
    #   run: |
    #     sudo apt update
    #     sudo apt install clang
    #     clang --version
        
    - name: Build all
      run: cargo build --workspace --all-targets --release
    - name: Run utreexo unit tests
      run: cargo test --workspace --all-targets --release

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        run: rustup toolchain install nightly

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Clippy
        run: rustup +nightly component add clippy rustfmt

      - name: Run fmt (nightly)
        run: cargo +nightly fmt --all -- --check

      - name: Run Clippy (nightly)
        run: cargo +nightly clippy -- -D warnings
